### ISSUE TITLE
请问 个人资料中的上传头像与修改昵称 失败是什么原因啊？

### ISSUE THREAD

**Issue by Jack1995** [HuRuWo/HuHuanChat#1]

**Comment by HuRuWo** [comment]
具体方法在 UserProfileActivity 的 uploadUserAvatar 里面
转到 UserProfileManager的uploadUserAvatar方法 里面获取一个 avatarUrl
而这个avatarUrl  来自  uploadParseAvatar  

uploadParseAvatar里面只是把数据存入数据库(而且还失败了) 所以这个demo并没有提供真正的头像更换方法。

http://docs.easemob.com/start/490integrationcases/10nickname

可以看到,真正的头像更新应该在你自己的app端，而不是在环信的后台

**Comment by HuRuWo** [comment]
具体就是,app端更新头像(得到头像URL)，然后用上面两种方式中的一种去通知环信显示新的头像(即头像的url)。

而不是把头像放在环信的服务器

**Comment by Jack1995** [comment]
ok 解决了
